import matplotlib.pyplot as plt
import io
import base64
import pandas as pd # Needed for date handling/indexing

def create_usage_chart(df_raw, start_date, end_date):
    # Generates a total consumption over time chart and returns it as a Base64 string.
    # :param df_raw: DataFrame with columns ['timestamp', 'kwh_total']
    # 1. Plotting Setup and Data
    plt.style.use('seaborn-v0_8-whitegrid') # Use a clean, professional style
    plt.figure(figsize=(10, 4))
    
    # Use the specific columns generated by data_loader.py
    # x-axis: 'timestamp', y-axis: 'kwh_total'
    plt.plot(df_raw['timestamp'], df_raw['kwh_total'], color='#3498db', linewidth=2)
    
    # 2. Titles and Formatting
    plt.title(f'Total Consumption Trend ({start_date} to {end_date})', fontsize=14)
    plt.xlabel('Date', fontsize=12)
    plt.ylabel('Total Consumption (kWh)', fontsize=12)
    
    # Improve date axis readability
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    
    # 3. Save to In-Memory Buffer
    buf = io.BytesIO()
    
    # Save the figure to the buffer as a PNG image
    plt.savefig(buf, format='png', bbox_inches='tight')
    buf.seek(0)
    
    # 4. Encode and Clean Up
    image_base64 = base64.b64encode(buf.read()).decode('utf-8')
    
    plt.close() 
    
    return image_base64