services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: 11111 #This is the password for postgres user
    ports:
      - "5433:5432"
    command: postgres -c datestyle=ISO,DMY
    volumes:
      - pbl_data:/var/lib/postgresql/data
      # Mount initialization SQL to be run on container first start
      - ./data.sql:/docker-entrypoint-initdb.d/01-init.sql
volumes:
  pbl_data:

